export const NAVIGATION = {
  splash: 'splash screen',
  home: 'Home Screen',
  forgotpassword: 'Forgot Password',
  signin: 'SignIn Screen',
  signup: 'SignUp Screen',
  registeredAddress: 'Address Screen',
  jobcreate: 'Job Create',
  allJobs: 'Business ALLJobs',
  jobLead: 'Job Lead',
  addNewClient: 'Add New Client',
  jobInvoices: 'Job Invoices',
  jobEstimates: 'Job Estimates',
  paymentSuccess:'Payment Success Screen',
  clientEstimates: 'Client Estimates',
  jobDetails: 'Job Details Screen',
  jobdetailsNavigator: 'Job details Navigator',
  profile: 'Profile Screen',
  messages:'Messages',
  eta:"Expected Time of arrival",
  addNotes:'AddNotes Screen',
  jobStatus:'JobStatus Screen',
  existingClientList:'ExistingClientList Screen',
  chatBoard:'Chat Screen',
  clientDetailafterEdit:'Client Edit',
  jobType:"Job type list",
  adSource:"Ad Source",
  address:'Search Address screen',
  jobMessage:'jobMessage',
  countryList:'Country List Screen',
  stateList:'State List Screen',
  createclient:"Create client",
  imageShown:'ImageShown Screen',
  jobSchedule:'Job Schedule Screen',
  clientDetails:'Client Details Screen',
  jobTags:'Job Tags Screen',
  team:"Team Screen",
  addQuantityItems:"Quantity Items",
  schedule:'schedule',
  editJobDetails:'Edit Job Details',
  editImage:'Edit Image Screen',
  CreateProfile:'Create Profile',
  BusinessSelection:'Business Selection',
  BusinessWork:'Choose Buisness Members',
  Notification:'Notification',
  ScheduleFilters:'Schedule Filters',
  MapViews:'MapViews',
  CreateInvoice:'Create Invoice',
  InvoiceItems:'Invoice Items',
  ItemQuantity:'Item Quantity',
  SelectClient:'Select Client',
  SelectEstimateClient:'Select EstClient',
  InvoicePayments:'Invoice Payments',
  InvoiceSignatures:'Invoice Signatures',
  InvoiceNotes:'Invoice Notes',
  Invoice:'Invoice',
  Timeline:'Timeline',
  Payment:'Payment',
  Quotes:'Quotes',
  Files:'Files',
  JobAllDetails:'JobAllDetails',
  ETANavigator:'ETANavigator',
  clientInvoices:'Client Invoices',
  clientJob:'Client Jobs',
  drawer:'Drawer Navigation',
  InvoiceAttachments:'Invoice Attachments',
  CreateEstimate:'Create Estimate',
  Chatting:'Chatting',
  jobAttachmentsList:'Attchments Lists'
};

export const TABS = {
  home: 'Home',
  jobSchedule: 'Schedule',
  messages: 'Messages',
  existingClientList: 'Client',
  createjob: 'Add',
  addBottomSheet: 'New Job',
  jobcreate: 'Job Create',
  // jobDetails:'JobDetails'
};
export const Drawers = {
  home:'Home',
  timesSheet: 'Timesheets',
  jobs: 'Jobs',
  leads: 'Leads',
  invoices: 'Invoices',
  estimates: 'Estimates',
  setting: 'Settings',
  getHelp: 'Get Help'
};
export const ETA = {
  onmyway: 'On My Way',
  late: 'Late',
};
export const JOB = {
  details: 'details',
  actions: 'actions',
  timeline: 'Timeline',
  jobschedule: 'JobSchedule',
  Invoice: 'Invoice',
}